spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Roome
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api
  port: 7070